name: Elixir CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: 1.9.4
        otp-version: 22.2
    - name: Install Dependencies
      run: mix deps.get
    - name: Run credo
      run: mix credo --strict
    - name: Run Tests
      run: mix test
